# Generated by Django 5.0.9 on 2025-01-14 12:38

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectsDetected',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('scan_number', models.IntegerField()),
                ('date_scanned', models.DateTimeField(default=datetime.datetime.now)),
                ('defects_detected', models.JSONField(max_length=50)),
                ('scanned_image', models.CharField(max_length=255)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
