# Generated by Django 5.0.9 on 2025-01-15 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_defectsdetected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batchsession',
            old_name='user_id',
            new_name='user',
        ),
    ]
