# Generated by Django 5.0.9 on 2025-01-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_user_id_batchsession_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchsession',
            name='batch_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
