# Generated by Django 5.0.9 on 2025-01-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_batchsession_batch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectsdetected',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
