# Generated by Django 5.0.9 on 2025-01-16 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_defectsdetected_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectsdetected',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.batchsession'),
        ),
    ]
