# Generated by Django 5.0.9 on 2025-01-22 05:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_defectsdetected_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchsession',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='defectsdetected',
            name='date_scanned',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
