# Generated by Django 5.0.9 on 2025-05-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_batchsession_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defectsdetected',
            name='scanned_image2',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
