"""empty message

Revision ID: 88437787a1a8
Revises: a3e28f1dc9b4
Create Date: 2024-12-19 12:13:44.240907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88437787a1a8'
down_revision = 'a3e28f1dc9b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defects_detected', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scanned_image', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defects_detected', schema=None) as batch_op:
        batch_op.drop_column('scanned_image')

    # ### end Alembic commands ###
