"""empty message

Revision ID: be7b5eb8169a
Revises: 88437787a1a8
Create Date: 2024-12-25 20:10:50.464938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be7b5eb8169a'
down_revision = '88437787a1a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('edu')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edu', sa.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
